---
title: "Exercices Quarto"
date-modified: today
css: ../styles/exercices.css
format: 
  html:
    self-contained: true
    code-fold: true
    code-tools: true
    number-sections: true
    output-file: exercices_corriges_quarto.html
  pdf: 
    output-file: exercices_corriges_quarto.pdf
crossref:
  fig-prefix: figure
  fig-title:  Figure
  tbl-prefix: tableau
  tbl-title:  Tableau
  title-delim: " &ndash; "
toc: true
editor: source
lang: fr
editor_options: 
  chunk_output_type: console
execute: 
  eval: true
  echo: true
  warning: false
---

```{r}
#| label: setup
#| echo: true

library(readr)
library(dplyr)
```


## Présentation des données {.unnumbered}

```{r}
#| label: donnees
#| echo: true

ra <- read_rds("donnees/ra_2020.rds")
```


## Produire un document simple {#doc-simple}


### Afficher un tableau

```{r}
#| label: tbl-ra

ra
```

## HTML avec éléments interactifs


## PDF


## Tableau de bord



## Méta {.unnumbered}

```{r}
#| label: source-et-forge
#| echo: false
#| eval: true
#| warning: false

meta_qmd_source <- xfun::with_ext(knitr::current_input(dir = TRUE), "qmd") |> 
  stringr::str_replace("/var/data/nfs", "~")

meta_remote <- system("git remote -v", intern = TRUE)
meta_url <- if (any(grep(pattern = "^origin", x = meta_remote))) {
  meta_i <- grep(pattern = "^origin.*\\.git\\s\\(fetch\\)", x = meta_remote)
  gsub("\\.git\\s\\(fetch\\)", "", strsplit(meta_remote[meta_i], "\\t")[[1]][[2]])
} else {
  ""
}
```

Ce document est produit par :  
  *`r meta_qmd_source`*
  
```{r}
#| label: afficher-forge
#| eval: !expr meta_url != ""
#| echo: false
#| results: asis

cat("### Dépôt Git {.unnumbered}

Ce projet est versionné dans :  
[", meta_url, "](", meta_url, ")")
```



